version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGDATA=/var/lib/postgresql/pgdata
    ports:
      - 5433:5432
    env_file:
      - ./db.dev.env

  app:
    build:
      context: ./services/app
    command: gunicorn --bind 0.0.0.0:5000 run:app
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./app.dev.env
    depends_on:
      - db

  nginx:
    build:
      context: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  postgres_data: