version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: $${DATABASE}
      MYSQL_USER: $${DB_USER}
      MYSQL_PASSWORD: $${DB_PASSWORD}
    env_file:
      - ./db.dev.env
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: ./services/app
    command: gunicorn --bind 0.0.0.0:5000 run:app
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ./app.dev.env
    depends_on:
      - db

  nginx:
    build:
      context: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  db-data:
